# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: CodeCoverageCommenter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Generate typings for scss files
      run: yarn scss:build

    - name: Run tests
      run: yarn jest --ci

    - name: Publish code coverage
      uses: 5monkeys/cobertura-action@master
      with:
        path: ${{ github.workspace }}/test-results/unit/coverage/cobertura-coverage.xml
        minimum_coverage: 85%

